### ISSUE TITLE
gtk-update-icon-cache: The generated cache was invalid.

### ISSUE THREAD

**Issue by rezso** [mate-desktop/mate-icon-theme-faenza#10]
If I run the gtk-update-icon-cache command with -f -i -q options on matefaenza theme, I get this error message: gtk-update-icon-cache: The generated cache was invalid.
After removing the index.theme, this command generates an .icon-theme.cache file.

**Comment by NiceandGently** [comment]
The index.theme file is needed, otherwise the theme won't display in mate-appearance-properties.
Can you try
```
/usr/bin/gtk-update-icon-cache -f /usr/share/icons/matefaenza &> /dev/null || :
/usr/bin/gtk-update-icon-cache -f /usr/share/icons/matefaenzadark &> /dev/null || :
/usr/bin/gtk-update-icon-cache -f /usr/share/icons/matefaenzagray &> /dev/null || :
```

**Comment by rezso** [comment]
I tried again. /usr/bin/gtk-update-icon-cache -f /usr/share/icons/matefaenza &> /dev/null || : suppresses the error message: 
root@papi:/usr/share/icons/matefaenza# gtk-update-icon-cache -q -t -f /usr/share/icons/matefaenza
gtk-update-icon-cache: The generated cache was invalid.

root@papi:/usr/share/icons/matefaenza# gtk-update-icon-cache -f /usr/share/icons/matefaenzadark
gtk-update-icon-cache: Cache file created successfully.

root@papi:/usr/share/icons/matefaenza# gtk-update-icon-cache -f /usr/share/icons/matefaenzagray
gtk-update-icon-cache: Cache file created successfully.

Weird, but I try to copy the content of .xz file with mc, it reports existing files in matefaenza/mimetypes/32. Looking into the matefaenza/mimetypes/32 in the archive, I see weird filenames, e.g. "gnome-mime-application-vnd.oasis.opendocument.f"
I downloaded the package from this git source, all filename good.
Weird.

**Comment by NiceandGently** [comment]
gnome-mime-application-vnd.oasis.opendocument.formula.png displays well in the 1.8.0 tarball here, opened with engrampa.
But i can confirm that gtk-update-icon-cache generates an error with matefaenza directory.
I quess that it is the same issue as here.
https://github.com/mate-desktop/mate-icon-theme-faenza/issues/11

**Comment by NiceandGently** [comment]
Thanks for reporting the issue.
https://github.com/mate-desktop/mate-icon-theme-faenza/commit/52a555a8795c33873a513071a74da01812098911
