### ISSUE TITLE
Icon "system-restart" should be named "system-reboot"

### ISSUE THREAD

**Issue by radioactiveman** [mate-desktop/mate-icon-theme-faenza#12]
According to the freedesktop specifcation [1] "system-reboot" should be used instead of "system-restart".

[1] http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names

**Comment by NiceandGently** [comment]
OK, but do you see an issue in menus?
Which distro?

**Comment by radioactiveman** [comment]
Yes, I see an issue in Xfce 4.12 (Arch Linux). The panel uses this icon in the menu and in the logout dialog.

If you don't want to remove the old icon, I suggest to use a symlink.

http://git.xfce.org/xfce/xfce4-panel/commit/?id=f41489f8aec3f45338f5c2cdb93c4a5e35ae427e
https://bugzilla.xfce.org/show_bug.cgi?id=11513

**Comment by NiceandGently** [comment]
np, i will add a symlink to be shure not break other menus.

**Comment by radioactiveman** [comment]
Thanks for the fast response. Make sure to fix mate-themes as well.

**Comment by NiceandGently** [comment]
done
https://github.com/mate-desktop/mate-icon-theme-faenza/commit/ef7368fa4eb78ad000258445c274b3f3b5aa21a4
