### ISSUE TITLE
missing file configure in the mate-icon-theme-faenza-1.10.0 

### ISSUE THREAD

**Issue by pantera31752** [mate-desktop/mate-icon-theme-faenza#13]

**Comment by NiceandGently** [comment]
run 'autoreconf -fi' for the moment, please

**Comment by pantera31752** [comment]
ok

**Comment by pantera31752** [comment]
gentoo linux mate-icon-theme-faenza-1.10.0 # autoreconf -fi
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'

**Comment by pantera31752** [comment]
Are you can downloading to http://pub.mate-desktop.org/releases/1.10/ ?

**Comment by NiceandGently** [comment]
reason for this is https://github.com/mate-desktop/mate-icon-theme-faenza/issues/11
In result we can't ship a generated tarball with a configure file for the moment
