### ISSUE TITLE
Sun Java icons

### ISSUE THREAD

**Issue by spvkgn** [mate-desktop/mate-icon-theme-faenza#14]
Original Faenza theme contains icons for Sun Java apps (symlinks of openJDK icon) and it would be useful if you can add support for these icons in this theme.

**Comment by NiceandGently** [comment]
Can you give me the name(s) of the symlink?

**Comment by spvkgn** [comment]
```
~ $ ls -l /usr/share/icons/Faenza/apps/16/sun-j*
lrwxrwxrwx 1 root root 13 дек.  16  2012 /usr/share/icons/Faenza/apps/16/sun-java6.png -> openjdk-6.png
lrwxrwxrwx 1 root root 13 дек.  16  2012 /usr/share/icons/Faenza/apps/16/sun-java7.png -> openjdk-6.png
lrwxrwxrwx 1 root root 13 дек.  16  2012 /usr/share/icons/Faenza/apps/16/sun-java.png -> openjdk-6.png
lrwxrwxrwx 1 root root 13 дек.  16  2012 /usr/share/icons/Faenza/apps/16/sun-javaws.png -> openjdk-6.png
lrwxrwxrwx 1 root root 13 дек.  16  2012 /usr/share/icons/Faenza/apps/16/sun-jcontrol.png -> openjdk-6.png
```

**Comment by NiceandGently** [comment]
Hmm, those icons was removed with
https://github.com/mate-desktop/mate-icon-theme-faenza/commit/c1478671383a3c7960714b31f2bdc480535e4f98
We had several downstream reports about not to ship this unlegal icons.
https://bugzilla.redhat.com/show_bug.cgi?id=1005464
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760676
But i'm not shure if this removal was Ok in case of the symlinks to openjdk.
@flexiondotorg
@sunweaver
What do you think?

**Comment by sunweaver** [comment]
@sunweaver: don't ship unlegal icons. Also SUN Java is obsolete. License-wise, don't think about shipping Oracle Java icons, instead.

**Comment by lukefromdc** [comment]
Oracle has such a dirty reputation their work should not be touched with a ten foot pole. Their name, their reputation, and their lawyers are a vicious tar pit best avoided by complete boycott

**Comment by raveit65** [comment]
OK.
