### ISSUE TITLE
Duplicate icons between matefaenzadark and matefaenzagray

### ISSUE THREAD

**Issue by ztefn** [mate-desktop/mate-icon-theme-faenza#16]
Hi there!

While working on the icons for Haguichi I noticed all icons for matefaenzadark and matefaenzagray looked the exactly the same but where not symlinked or something like that.

Using Meld diff viewer on both folders they appeared to be 99% equal with exception of of a few lost icons and the actions folders, which appears to be a copy of matefaenza/actions.

Have you considered to make matefaenzagray inherit matefaenzadark inside the theme index instead of matefaenza and then only fill matefaenzagray with a symlinked actions folder to matefaenza/actions? This could remove more than 3000 duplicate icons and save 4mb for free.

Or am I missing somethting here?

**Comment by infirit** [comment]
Not sure you can inherit more than once but if you are willing to try it out and try to reduce the size please do :+1: :smile:.

**Comment by ztefn** [comment]
Okay then, I'll give it a try! :)

**Comment by ztefn** [comment]
How about that?! =D

**Comment by NiceandGently** [comment]
looks good :)
.......are you interested to maintain mate-icon-theme-faenza?
.... my favorite interest is mate-themes and that's enough work....
.....former maintainer of mate-icon-theme-faenza is not exists anymore......

**Comment by ztefn** [comment]
What are the tasks the maintainer is expected to do exactly? I know a few things about icons, but I'm not familiar with the build and release process.

**Comment by NiceandGently** [comment]
Normaly a icon-theme do not cause much work :)
One task is to check PRs and apply them or not........like here.
Sometimes checking upstream (faenza) for changes and improvements.
Maybe adding missing icons......
And preparing new releases wich is mostly git work, but here you have all help from us.
So, if you like to do this visit us at irc freenode chanel #mate-dev.

.... thank you

**Comment by ztefn** [comment]
I'm okay to help around further sanitizing the theme, checking pull requests and fixing issues. But I don't think I'm passionate enough about Faenza to commit to full maintainership...

Nevertheless, I do love the Mate project in general so let me know if you need help with other (icon) artwork too. Having a daytime job and also running a small [project](https://www.haguichi.net/) of my own, drive-by and timeframe-less contributions are best suitable...

On freenode my nick is the same (ztefn) and I shall drop by on #mate-dev every now and then.
